version: "3.9"

services:
  web:
    build: .
    container_name: django_web
    restart: unless-stopped

    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn hims_kb.wsgi:application --bind 0.0.0.0:8000
      "

    volumes:
      - .:/app
      - static_volume:/vol/static
      - media_volume:/vol/media

    ports:
      - "8000:8000"

    environment:
      DJANGO_SETTINGS_MODULE: hims_kb.settings
      DB_ENGINE: sqlite
      REDIS_HOST: redis
      REDIS_PORT: 6379

    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped

    command: redis-server --appendonly yes

    volumes:
      - redis_data:/data

    ports:
      - "6379:6379"

volumes:
  redis_data:
  static_volume:
  media_volume: