apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: calvin-arieri

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      imagePullSecrets:
        - name: ecr-secret

      containers:
        - name: backend
          image: IMAGE_BACKEND
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: SECRET_KEY

            - name: DEBUG
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: DEBUG

            - name: ALLOWED_HOSTS
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: ALLOWED_HOSTS

            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DB_PORT

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DB_PASSWORD

            - name: REDIS_HOST
              value: redis-service

            - name: REDIS_PORT
              value: "6379"

          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5