apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: calvin-arieri

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      imagePullSecrets:
        - name: ecr-secret

      containers:
        - name: backend

          image: IMAGE_BACKEND

          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          env:

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: SECRET_KEY

            - name: DEBUG
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: DEBUG

            - name: ALLOWED_HOSTS
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: ALLOWED_HOSTS


            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: POSTGRES_HOST

            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: POSTGRES_PORT

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: POSTGRES_PASSWORD


            - name: REDIS_HOST
              value: redis-service

            - name: REDIS_PORT
              value: "6379"


          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"


          livenessProbe:
            httpGet:
              path: /health/
              port: 8000

            initialDelaySeconds: 40
            periodSeconds: 15


          readinessProbe:
            httpGet:
              path: /health/
              port: 8000

            initialDelaySeconds: 20
            periodSeconds: 10