apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: calvin-arieri

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      imagePullSecrets:
        - name: ecr-secret

      containers:
        - name: backend

          image: IMAGE_BACKEND

          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          env:

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: SECRET_KEY

            - name: DEBUG
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: DEBUG

            - name: ALLOWED_HOSTS
              value: "*"

            - name: DB_ENGINE
              value: sqlite

            - name: REDIS_HOST
              value: redis-service

            - name: REDIS_PORT
              value: "6379"


          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"


          startupProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12

          livenessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 40
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 6

          readinessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6